device, vga: Fix unused-function error for update_screen()
The following error happens on some compilers if vga_update_screen() is not finished

src/device/vga.c:59:20: error: unused function 'update_screen' [-Werror,-Wunused-function]
   59 | static inline void update_screen() {
      |

Students may remove the "static inline void update_screen() UNUSED;" line
after they've finished vga_update_screen()

Signed-off-by: snnbyyds <snnbyyds@gmail.com>